// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvTH47EYmQZY7rwavIGCzEHXEnhrG31IM',
    appId: '1:1008237590273:web:30d59f2018a6e0d4404d00',
    messagingSenderId: '1008237590273',
    projectId: 'quizletappfinalproject',
    authDomain: 'quizletappfinalproject.firebaseapp.com',
    databaseURL: 'https://quizletappfinalproject-default-rtdb.firebaseio.com',
    storageBucket: 'quizletappfinalproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjg69rQCXS_RMIgKHi6mnTs6p15cPwROU',
    appId: '1:1008237590273:android:d2ba696438f9a2d9404d00',
    messagingSenderId: '1008237590273',
    projectId: 'quizletappfinalproject',
    databaseURL: 'https://quizletappfinalproject-default-rtdb.firebaseio.com',
    storageBucket: 'quizletappfinalproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPPE_bdbJ_it3Y-jXDrsID-lZuBo7NKI',
    appId: '1:1008237590273:ios:1e0b4909fb6f7fa9404d00',
    messagingSenderId: '1008237590273',
    projectId: 'quizletappfinalproject',
    databaseURL: 'https://quizletappfinalproject-default-rtdb.firebaseio.com',
    storageBucket: 'quizletappfinalproject.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbPPE_bdbJ_it3Y-jXDrsID-lZuBo7NKI',
    appId: '1:1008237590273:ios:1e0b4909fb6f7fa9404d00',
    messagingSenderId: '1008237590273',
    projectId: 'quizletappfinalproject',
    databaseURL: 'https://quizletappfinalproject-default-rtdb.firebaseio.com',
    storageBucket: 'quizletappfinalproject.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvTH47EYmQZY7rwavIGCzEHXEnhrG31IM',
    appId: '1:1008237590273:web:8792b07e4901febd404d00',
    messagingSenderId: '1008237590273',
    projectId: 'quizletappfinalproject',
    authDomain: 'quizletappfinalproject.firebaseapp.com',
    databaseURL: 'https://quizletappfinalproject-default-rtdb.firebaseio.com',
    storageBucket: 'quizletappfinalproject.appspot.com',
  );
}
